#Page d'accueil
oc_platform_home:
    path:   /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page:   \d*

#Page de visualisation d'une annonce
oc_platform_view:
    path:   /advert/{id}
    defaults: 
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+

#Page d'ajout d'une annonce
oc_platform_add:
    path:   /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

#Page d'édition d'une annonce        
oc_platform_edit:
    path:   /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

#Page de suppression d'une annonce       
oc_platform_delete:
    path:   /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+
        
#Page de test
oc_platform_test:
    path:   /test
    defaults:
        _controller: OCPlatformBundle:Advert:test
    