services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"
